"""Roblox asset kit: builds game-ready low-poly models in Blender from code.

Every asset is generated by a script, so it can be rebuilt, tweaked and re-exported at any time.
Each build writes, per asset:
    <out>/<Asset>.fbx          ready for the Roblox 3D Importer (texture embedded)
    <out>/T_<Asset>.png        the asset's color texture (for SurfaceAppearance / TextureID)
    <out>/<Asset>_preview.png  a rendered preview to check the model without opening Blender
    <out>/<Asset>.blend        editable source scene
and prints a report line (tris, size in studs, pivot).

Run with the Blender app:
    blender -b -P blox-game/blender/rbx_asset_kit.py -- --asset all --out blox-game/blender/exports
or with the `bpy` Python module (pip install bpy):
    python blox-game/blender/rbx_asset_kit.py --asset fruit:gomu_gomu --out blox-game/blender/exports

--asset accepts: all | fruits | swords | fruit:<id> | sword:<id>   (ids: gomu_gomu, mera_mera, enma, ...)
Units: 1 Blender unit = 1 Roblox stud. In the Roblox 3D Importer set File Dimensions to "Studs".
"""

import argparse
import math
import os
import sys

import bpy  # must come before bmesh when running as the bpy module
import bmesh
import numpy as np

# ---------------------------------------------------------------------------
# Content data (keep in sync with the Content Bible in BLOX_FRUITS_MASTER_PROMPT.md)
# ---------------------------------------------------------------------------

# Canon One Piece Devil Fruits. Colors follow the series where the fruit has been shown (Gomu Gomu, Mera Mera,
# Ope Ope, Yami Yami); the rest are colored after the user's power.
# base: body color, swirls: stripe colors (cycled per arm), stem/leaf colors.
# Shape: squash (height scale), pear (top taper), lobes/lobe_depth (ridges), heart (Ope Ope), arms/twist (swirls).
FRUITS = {
    "bara_bara":    dict(base="#e04848", swirls=["#f4f0e8"], stem="#3a2a2a", leaf="#4f8f3a", arms=3, twist=1.4),
    "supa_supa":    dict(base="#8f99a6", swirls=["#dfe5ec"], stem="#3b3f44", leaf="#6f8a5a", lobes=8, lobe_depth=0.05),
    "horo_horo":    dict(base="#f2a6c8", swirls=["#2a2030"], stem="#2a2030", leaf="#c86aa0", arms=3, twist=1.8),
    "hana_hana":    dict(base="#e86a9a", swirls=["#ffd1e2"], stem="#2f6a3a", leaf="#5fbf5a", lobes=5, lobe_depth=0.09),
    "moku_moku":    dict(base="#c9ccd1", swirls=["#f7f8fa"], stem="#4a4e55", leaf="#8a9aa0", arms=3, twist=1.2),
    "suna_suna":    dict(base="#d9b26a", swirls=["#f2dca6"], stem="#6a4a22", leaf="#9aa04a", pear=0.12, arms=4, twist=2.0),
    "mera_mera":    dict(base="#e8551f", swirls=["#ffc93c"], stem="#3a2a22", leaf="#ff8a2f", pear=0.10, arms=3, twist=1.8),
    "hie_hie":      dict(base="#8fd3f5", swirls=["#ffffff"], stem="#3a6a8a", leaf="#bfeaff", lobes=6, lobe_depth=0.04),
    "goro_goro":    dict(base="#2a3f8f", swirls=["#ffe14d"], stem="#1a2240", leaf="#5a7fff", arms=4, twist=2.6),
    "gomu_gomu":    dict(base="#7b3fa0", swirls=["#b788dc"], stem="#2f5a2a", leaf="#5aa04a", arms=4, twist=1.6),
    "pika_pika":    dict(base="#ffd93b", swirls=["#fff6c4"], stem="#8a6a1a", leaf="#e0c040", arms=5, twist=1.2),
    "magu_magu":    dict(base="#7a1a12", swirls=["#ff6a1f"], stem="#2a1210", leaf="#c0401a", lobes=7, lobe_depth=0.06),
    "ope_ope":      dict(base="#d6336c", swirls=["#f59ab8"], stem="#3a1a2a", leaf="#4f8f4a", heart=1.0, arms=3, twist=1.0),
    "ito_ito":      dict(base="#ff6fb0", swirls=["#ffd1e6"], stem="#5a2a40", leaf="#ff9ad0", arms=6, twist=3.0),
    "mochi_mochi":  dict(base="#f4ecd8", swirls=["#d6c39a"], stem="#7a6a4a", leaf="#a8b07a", squash=0.9, arms=3, twist=1.0),
    "neko_leopard": dict(base="#e0b040", swirls=["#5a3a10"], stem="#3a2a10", leaf="#8a7a2a", arms=5, twist=2.4),
    "yami_yami":    dict(base="#3a1f4f", swirls=["#7a4fa0"], stem="#140a1c", leaf="#4a2a6a", lobes=5, lobe_depth=0.11),
    "gura_gura":    dict(base="#e8e2cf", swirls=["#7a7468"], stem="#4a4438", leaf="#9a9a7a", lobes=6, lobe_depth=0.05),
    "tori_phoenix": dict(base="#2f7fe0", swirls=["#ffe066"], stem="#1a3a6a", leaf="#4fd0ff", squash=1.12, arms=3, twist=1.6),
    "uo_seiryu":    dict(base="#2a6fb0", swirls=["#9fdcff"], stem="#153a5a", leaf="#3fa0c0", squash=1.1, arms=4, twist=2.2),
}

# Canon swords. Lengths in studs; curve = tip offset sideways; guard "round" (tsuba) or "cross".
SWORDS = {
    "marine_saber":    dict(blade_len=3.0, blade_w=0.20, curve=0.12, blade="#d9dee6", edge="#ffffff",
                            guard="#c9a24a", handle="#1f2f5a", pommel="#c9a24a", guard_r=0.22, handle_len=0.9),
    "wado_ichimonji":  dict(blade_len=3.5, blade_w=0.17, curve=0.16, blade="#dfe4ea", edge="#ffffff",
                            guard="#c9a24a", handle="#f4f4f0", pommel="#c9a24a", guard_r=0.22, handle_len=1.0),
    "sandai_kitetsu":  dict(blade_len=3.4, blade_w=0.17, curve=0.17, blade="#cfd5dc", edge="#f2f2f2",
                            guard="#b08a3a", handle="#8a1c1c", pommel="#b08a3a", guard_r=0.23, handle_len=1.0),
    "shusui":          dict(blade_len=3.7, blade_w=0.18, curve=0.18, blade="#1c1c20", edge="#6a6a72",
                            guard="#2a2a2a", handle="#5a1a1a", pommel="#2a2a2a", guard_r=0.24, handle_len=1.05),
    "enma":            dict(blade_len=3.7, blade_w=0.18, curve=0.18, blade="#d4dbe6", edge="#eef2ff",
                            guard="#d4a93a", handle="#4a2a6a", pommel="#d4a93a", guard_r=0.24, handle_len=1.05),
    "yoru":            dict(blade_len=5.4, blade_w=0.28, curve=0.0, blade="#141414", edge="#2e2e2e",
                            guard="#d4a93a", handle="#1f2a4a", pommel="#d4a93a", guard_r=0.24, handle_len=1.3,
                            guard_type="cross"),
}

TRI_BUDGET = {"fruit": 2000, "sword": 3000}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def hex_rgb(h):
    h = h.lstrip("#")
    return np.array([int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4)])


def reset_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.scale_length = 1.0
    return scene


def bm_to_object(bm, name):
    mesh = bpy.data.meshes.new(name)
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.scene.collection.objects.link(obj)
    return obj


def paint_uv(bm, uv):
    """Point every loop of a part at one swatch of the texture, giving the part a flat color."""
    layer = bm.loops.layers.uv.verify()
    for face in bm.faces:
        for loop in face.loops:
            loop[layer].uv = uv


def swatch_texture(name, colors, size=64):
    """Square texture split into a grid of flat color swatches. Returns (image_pixels, uv centers)."""
    n = math.ceil(math.sqrt(len(colors)))
    cell = size // n
    px = np.ones((size, size, 4))
    uvs = []
    for i, c in enumerate(colors):
        cx, cy = i % n, i // n
        px[cy * cell:(cy + 1) * cell, cx * cell:(cx + 1) * cell, :3] = hex_rgb(c)
        uvs.append(((cx + 0.5) / n, (cy + 0.5) / n))
    return px, uvs


def make_image(name, px, out_dir):
    h, w = px.shape[:2]
    img = bpy.data.images.new(name, w, h, alpha=False)
    img.pixels.foreach_set(px.astype(np.float32).ravel())
    img.filepath_raw = os.path.join(out_dir, name + ".png")
    img.file_format = "PNG"
    img.save()
    return img


def make_material(name, img, roughness, metallic=0.0):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nodes, links = mat.node_tree.nodes, mat.node_tree.links
    bsdf = nodes.get("Principled BSDF") or nodes.new("ShaderNodeBsdfPrincipled")
    tex = nodes.new("ShaderNodeTexImage")
    tex.image = img
    tex.interpolation = "Closest"  # crisp swatches
    links.new(tex.outputs["Color"], bsdf.inputs["Base Color"])
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["Metallic"].default_value = metallic
    return mat


def join(objs, name):
    bpy.ops.object.select_all(action="DESELECT")
    for o in objs:
        o.select_set(True)
    bpy.context.view_layer.objects.active = objs[0]
    bpy.ops.object.join()
    obj = bpy.context.view_layer.objects.active
    obj.name = obj.data.name = name
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    return obj


def tri_count(obj):
    return sum(len(p.vertices) - 2 for p in obj.data.polygons)


# ---------------------------------------------------------------------------
# Fruits
# ---------------------------------------------------------------------------

SPHERE_V0 = 0.125  # sphere UVs use the top 7/8 of the texture; the bottom strip holds stem/leaf swatches


def fruit_texture(look, size=256):
    """Swirl pattern in equirectangular space with dark outlines on the stripes (anime look)."""
    base, swirls = hex_rgb(look["base"]), [hex_rgb(c) for c in look["swirls"]]
    arms, twist = look.get("arms", 3), look.get("twist", 1.5)
    px = np.ones((size, size, 4))
    sphere_rows = int(size * (1 - SPHERE_V0))
    strip = size - sphere_rows

    u = (np.arange(size) + 0.5) / size
    v = (np.arange(sphere_rows) + 0.5) / sphere_rows
    U, V = np.meshgrid(u, v)
    k = arms * U + twist * V  # arm coordinate: integer part picks the arm, fraction is position across it
    frac = k - np.floor(k)
    arm = np.floor(k).astype(int) % len(swirls)
    width = 0.34
    stripe = frac < width
    edge = stripe & ((frac < 0.035) | (frac > width - 0.035))

    img = np.broadcast_to(base, U.shape + (3,)).copy()
    for i, c in enumerate(swirls):
        img[stripe & (arm == i)] = c
    img[edge] = img[edge] * 0.55
    # soft vertical shading baked in: slightly darker toward the bottom
    img *= (0.82 + 0.18 * V)[..., None]
    px[strip:, :, :3] = img

    # bottom strip: stem (left half) and leaf (right half)
    px[:strip, : size // 2, :3] = hex_rgb(look["stem"])
    px[:strip, size // 2:, :3] = hex_rgb(look["leaf"])
    stem_uv = (0.25, SPHERE_V0 / 2)
    leaf_uv = (0.75, SPHERE_V0 / 2)
    return px, stem_uv, leaf_uv


def build_fruit(fid, out_dir):
    look = FRUITS[fid]
    name = "Fruit_" + "".join(p.capitalize() for p in fid.split("_"))
    radius = 0.8  # 1.6 stud diameter, readable in a player's hand
    squash, pear = look.get("squash", 1.0), look.get("pear", 0.0)
    lobes, lobe_depth = look.get("lobes", 0), look.get("lobe_depth", 0.0)
    heart = look.get("heart", 0.0)

    px, stem_uv, leaf_uv = fruit_texture(look)
    img = make_image("T_" + name, px, out_dir)

    # Body
    bm = bmesh.new()
    bm.loops.layers.uv.new()  # calc_uvs only fills an existing UV layer
    bmesh.ops.create_uvsphere(bm, u_segments=28, v_segments=16, radius=radius, calc_uvs=True)
    for vert in bm.verts:
        x, y, z = vert.co
        t = z / radius  # -1..1
        theta = math.atan2(y, x)
        r = 1.0
        if lobes:
            r += lobe_depth * math.cos(lobes * theta) * (1 - t * t)
        r *= 1 - pear * max(t, 0.0)
        z *= squash
        if heart:  # two bumps on top, a point at the bottom
            r *= 1 - 0.55 * heart * max(-t, 0.0) ** 1.3
            z *= 1 + 0.3 * heart * max(-t, 0.0)
            z -= heart * 0.35 * radius * max(t, 0.0) ** 2 * max(0.0, 1 - abs(x) / (radius * 0.55))
        z -= 0.10 * radius * max(t, 0.0) ** 10  # dimple where the stem sits
        vert.co = (x * r, y * r, z)
    uv = bm.loops.layers.uv.verify()
    for face in bm.faces:
        for loop in face.loops:
            uu, vv = loop[uv].uv
            loop[uv].uv = (uu, SPHERE_V0 + vv * (1 - SPHERE_V0))
    for face in bm.faces:
        face.smooth = True
    body = bm_to_object(bm, name + "_body")
    top = radius * squash * 0.9 - heart * 0.3 * radius

    # Stem: slightly bent, tapered
    bm = bmesh.new()
    bmesh.ops.create_cone(bm, cap_ends=True, cap_tris=False, segments=6, radius1=0.07, radius2=0.045, depth=0.42)
    paint_uv(bm, stem_uv)
    stem = bm_to_object(bm, name + "_stem")
    stem.location = (0.03, 0, top + 0.17)
    stem.rotation_euler = (0, math.radians(14), 0)

    # Leaf: flattened ellipsoid, a closed volume so it renders from both sides
    bm = bmesh.new()
    bmesh.ops.create_uvsphere(bm, u_segments=8, v_segments=4, radius=1.0)
    bmesh.ops.scale(bm, vec=(0.34, 0.14, 0.03), verts=bm.verts)
    paint_uv(bm, leaf_uv)
    leaf = bm_to_object(bm, name + "_leaf")
    leaf.location = (0.30, 0.02, top + 0.18)
    leaf.rotation_euler = (math.radians(10), math.radians(-28), math.radians(20))

    obj = join([body, stem, leaf], name)
    obj.data.materials.append(make_material("M_" + name, img, roughness=0.25))
    return obj, "fruit"


# ---------------------------------------------------------------------------
# Swords (origin at the grip; blade points +Z in Blender = +Y in Roblox)
# ---------------------------------------------------------------------------

def build_sword(sid, out_dir):
    s = SWORDS[sid]
    name = "Sword_" + "".join(p.capitalize() for p in sid.split("_"))
    colors = [s["blade"], s["edge"], s["guard"], s["handle"], s["pommel"]]
    px, uvs = swatch_texture(name, colors)
    img = make_image("T_" + name, px, out_dir)
    blade_uv, edge_uv, guard_uv, handle_uv, pommel_uv = uvs

    hl = s["handle_len"]
    guard_z = hl / 2 + 0.03
    parts = []

    # Blade: a curved, tapered strip. Back (spine) colored blade, front sliver colored edge.
    segs = 12
    L, W, T, C = s["blade_len"], s["blade_w"], 0.045, s["curve"]
    for part_uv, w0, w1 in ((blade_uv, -W / 2, W * 0.15), (edge_uv, W * 0.15, W / 2)):
        bm = bmesh.new()
        rings = []
        for i in range(segs + 1):
            t = i / segs
            z = guard_z + 0.03 + t * L
            off = C * t * t  # curve toward the edge side
            taper = 1.0 if t < 0.85 else max(0.0, 1 - (t - 0.85) / 0.15)
            a, b = w0 * taper + off, w1 * taper + off
            th = T * (0.5 if part_uv is edge_uv else 1.0) * max(taper, 0.15)
            ring = [bm.verts.new(p) for p in ((a, -th, z), (b, -th, z), (b, th, z), (a, th, z))]
            rings.append(ring)
        for r0, r1 in zip(rings, rings[1:]):
            for j in range(4):
                bm.faces.new((r0[j], r0[(j + 1) % 4], r1[(j + 1) % 4], r1[j]))
        bm.faces.new(list(reversed(rings[0])))
        bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=1e-4)
        bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
        paint_uv(bm, part_uv)
        parts.append(bm_to_object(bm, name + "_blade"))

    def cyl(r1, r2, depth, z, uv, segments=8, sx=1.0):
        bm = bmesh.new()
        bmesh.ops.create_cone(bm, cap_ends=True, cap_tris=False, segments=segments,
                              radius1=r1, radius2=r2, depth=depth)
        bmesh.ops.scale(bm, vec=(sx, 1.0, 1.0), verts=bm.verts)
        bmesh.ops.translate(bm, vec=(0, 0, z), verts=bm.verts)
        paint_uv(bm, uv)
        return bm_to_object(bm, name + "_part")

    if s.get("guard_type") == "cross":
        bm = bmesh.new()
        bmesh.ops.create_cube(bm, size=1.0)
        bmesh.ops.scale(bm, vec=(s["guard_r"] * 4.0, 0.14, 0.14), verts=bm.verts)
        bmesh.ops.translate(bm, vec=(0, 0, guard_z), verts=bm.verts)
        paint_uv(bm, guard_uv)
        parts.append(bm_to_object(bm, name + "_guard"))
    else:
        parts.append(cyl(s["guard_r"], s["guard_r"], 0.06, guard_z, guard_uv, segments=10, sx=1.25))
    parts.append(cyl(0.075, 0.07, hl, 0.0, handle_uv, segments=8))
    parts.append(cyl(0.09, 0.07, 0.08, -hl / 2 - 0.04, pommel_uv, segments=8))

    obj = join(parts, name)
    obj.data.materials.append(make_material("M_" + name, img, roughness=0.35, metallic=0.6))
    for p in obj.data.polygons:
        p.use_smooth = False
    return obj, "sword"


# ---------------------------------------------------------------------------
# Preview, checks, export
# ---------------------------------------------------------------------------

def render_preview(obj, path, res=512):
    scene = bpy.context.scene
    scene.render.engine = "CYCLES"
    scene.cycles.device = "CPU"
    scene.cycles.samples = 24
    scene.render.resolution_x = scene.render.resolution_y = res
    scene.render.film_transparent = False
    scene.view_settings.view_transform = "Standard"

    world = bpy.data.worlds.new("World")
    world.use_nodes = True
    world.node_tree.nodes["Background"].inputs["Color"].default_value = (0.16, 0.18, 0.24, 1)
    world.node_tree.nodes["Background"].inputs["Strength"].default_value = 1.0
    scene.world = world

    sun = bpy.data.objects.new("Sun", bpy.data.lights.new("Sun", "SUN"))
    sun.data.energy = 3.5
    sun.rotation_euler = (math.radians(50), 0, math.radians(35))
    scene.collection.objects.link(sun)

    corners = [obj.matrix_world @ v.co for v in obj.data.vertices]
    lo = np.min(np.array(corners), axis=0)
    hi = np.max(np.array(corners), axis=0)
    center, size = (lo + hi) / 2, float(np.max(hi - lo))

    cam = bpy.data.objects.new("Cam", bpy.data.cameras.new("Cam"))
    cam.data.type = "ORTHO"
    cam.data.ortho_scale = size * 1.3
    direction = np.array([1.0, -1.4, 0.7])
    direction /= np.linalg.norm(direction)
    cam.location = tuple(center + direction * size * 3)
    look = center - np.array(cam.location)
    cam.rotation_euler = (math.atan2(math.hypot(look[0], look[1]), -look[2]), 0,
                          math.atan2(look[1], look[0]) - math.pi / 2)
    cam.data.clip_end = size * 10
    scene.collection.objects.link(cam)
    scene.camera = cam

    scene.render.filepath = path
    bpy.ops.render.render(write_still=True)


def export(obj, kind, out_dir):
    name = obj.name
    tris = tri_count(obj)
    dims = obj.dimensions
    budget = TRI_BUDGET[kind]
    status = "OK" if tris <= budget else f"OVER BUDGET ({budget})"

    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    bpy.ops.export_scene.fbx(
        filepath=os.path.join(out_dir, name + ".fbx"),
        use_selection=True,
        apply_unit_scale=True,
        apply_scale_options="FBX_SCALE_UNITS",
        axis_forward="-Z",
        axis_up="Y",
        use_mesh_modifiers=True,
        mesh_smooth_type="FACE",
        add_leaf_bones=False,
        path_mode="COPY",
        embed_textures=True,
    )
    render_preview(obj, os.path.join(out_dir, name + "_preview.png"))
    bpy.ops.wm.save_as_mainfile(filepath=os.path.join(out_dir, name + ".blend"), compress=True)
    print(f"[asset] {name:<26} tris={tris:<5} size={dims.x:.2f}x{dims.y:.2f}x{dims.z:.2f} studs  "
          f"pivot=origin  {status}")
    return tris <= budget


def make_lineup(previews, path, cols=5, cell=256):
    """Contact sheet of previews so a whole batch can be checked in one image."""
    rows = -(-len(previews) // cols)
    sheet = None
    for i, p in enumerate(previews):
        img = bpy.data.images.load(p)
        w, h = img.size
        px = np.array(img.pixels[:]).reshape(h, w, 4)[:: max(1, h // cell), :: max(1, w // cell)][:cell, :cell]
        if sheet is None:  # fill empty cells with the preview background
            sheet = np.broadcast_to(px[0, 0], (rows * cell, cols * cell, 4)).copy()
        r, c = rows - 1 - i // cols, i % cols
        sheet[r * cell:r * cell + px.shape[0], c * cell:c * cell + px.shape[1]] = px
    img = bpy.data.images.new("lineup", sheet.shape[1], sheet.shape[0])
    img.pixels.foreach_set(sheet.astype(np.float32).ravel())
    img.filepath_raw = path
    img.file_format = "PNG"
    img.save()
    print(f"[lineup] {path}")


def build(asset, out_dir):
    kind, _, aid = asset.partition(":")
    reset_scene()
    if kind == "fruit":
        obj, k = build_fruit(aid, out_dir)
    elif kind == "sword":
        obj, k = build_sword(aid, out_dir)
    else:
        raise SystemExit(f"unknown asset '{asset}'")
    return export(obj, k, out_dir), os.path.join(out_dir, obj.name + "_preview.png")


def expand(asset):
    if asset == "all":
        return expand("fruits") + expand("swords")
    if asset == "fruits":
        return ["fruit:" + f for f in FRUITS]
    if asset == "swords":
        return ["sword:" + s for s in SWORDS]
    return [asset]


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else sys.argv[1:]
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--asset", default="all")
    parser.add_argument("--out", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "exports"))
    args = parser.parse_args(argv)
    out_dir = os.path.abspath(args.out)
    os.makedirs(out_dir, exist_ok=True)
    results = [build(a, out_dir) for a in expand(args.asset)]
    if len(results) > 1:
        make_lineup([p for _, p in results], os.path.join(out_dir, "_lineup.png"))
    if not all(ok for ok, _ in results):
        raise SystemExit("some assets are over their triangle budget")


if __name__ == "__main__":
    main()
